#
# S C E N E N
#

# M O V I E
- id : scene_movie
  trigger:
  - platform: state
    entity_id: input_boolean.scene_movie_on
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.scene_sleepy_home_on
  - service: input_boolean.turn_off
    entity_id: input_boolean.scene_general_on
  - service: switch.turn_off
    entity_id: group.kitchen
  - service:  switch.turn_off
    entity_id: group.living_room
  - service:  automation.turn_off
    entity_id: group.automata_lampak
  - service: rest_command.plafon_light
    data:
      state: true
      brightness: 150
      hue: 2047
  - service:  rest_command.fal_light
    data:
      state: true
      brightness: 150
      hue: 2047
  - service: media_player.turn_on
    entity_id: media_player.hometheater
  - delay: 0:07    
  - service: media_player.select_source
    data:
      entity_id: media_player.hometheater
      source: 'CBL/SAT'
  - delay: 0:07      
  - service: media_player.volume_set      
    data:
      entity_id: media_player.hometheater
      volume: 50
    
# S L E E P Y   H O M E

- id : scene_sleepy_home
  trigger:
  - platform: state
    entity_id: input_boolean.scene_sleepy_home_on
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.scene_movie_on
  - service: input_boolean.turn_off
    entity_id: input_boolean.scene_general_on
  - service: media_player.turn_off
    entity_id: media_player.hometheater
  - service: switch.turn_off
    entity_id: group.kitchen
  - service:  switch.turn_off
    entity_id: group.living_room
  - service: automation.turn_off
    entity_id: group.automata_lampak
  - service: light.turn_off
    entity_id: light.halofolyoso
  - service: light.turn_off
    entity_id: light.fal
  - service: light.turn_off
    entity_id: light.plafon
  - service: notify.iphone_von_tamas
    data:
      title: "Smart Home Alerts"
      message: "Something happened at home!"
      data:
        push:
          badge: 5
    
# G E N E R A L

- id: scene_general
  trigger:
  - platform: state
    entity_id: input_boolean.scene_general_on
    from: 'off'
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.scene_movie_on
  - service: input_boolean.turn_off
    entity_id: input_boolean.scene_sleepy_home_on    
  - service:  automation.turn_on
    entity_id: group.automata_lampak
  - service: light.turn_off
    entity_id: light.plafon
  - service: light.turn_off
    entity_id: light.fal

- id: scene_general_early_activation
  alias: General Scene reggel
  trigger: 
  - platform: time
    at: '06:20:00'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.scene_general_on
  
#
# S L E E P Y   M O V I N G
#
- id: sleepy_home_walking_bedroom_floor
  alias: Alvajárók a WC-re
  trigger:
  - platform: state
    entity_id: binary_sensor.halofoyosopir
    from: 'off'
    to: 'on'  
  - platform: state
    entity_id: binary_sensor.ep1
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.np1
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.sensor.daylight.attributes.daylight == False }}'
    - condition: template
      value_template: '{{ states.input_boolean.scene_sleepy_home_on.state == "on" }}'
    - condition: or
      conditions:
      - condition: time
        after: '22:00:00'
        before: '06:20:00'
  action:
  - service: light.turn_on
    data:
      entity_id: light.plafon
      brightness: 160
      rgb_color: [255,63,0]
  - service: light.turn_on
    data:
      entity_id: light.fal
      brightness: 160
      rgb_color: [255,63,0]
  - service: timer.start
    entity_id: timer.timer_sleepy_light_off
      
- id: sleepy_home_light_off
  alias: Alvajárok lámpa kikapcs
  trigger:
  - platform: event
    event_type: timer.finish
    event_data:
      entity_id: timer.timer_sleepy_light_off
  action:
  - service: light.turn_off
    entity_id: light.plafon
  - service: light.turn_off
    entity_id: light.fal
#
# K O N Y H A P U L T   M O Z I   K O Z B E N
#
- id: konyhapult_movie_light_on
  alias: Konyhapult világítás mozi közben
  trigger:
  - entity_id: binary_sensor.vpir_konyha_mootion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.konyhapult
    state: 'off'
  - condition: template
    value_template: '{{ states.input_boolean.scene_movie_on.state == "on" }}'
  action:
  - service: rest_command.konyhapult_movie_on
  - service: timer.start
    entity_id: timer.timer_konyhapult_movie_off

#
# K O N Y H A P U L T
#
- id: konyhapult_light_on
  alias: Konyhapult világítás
  trigger:
  - entity_id: binary_sensor.vpir_konyha_mootion
    platform: state
    to: 'on'  
  condition:  
  - condition: template
    value_template: '{{ states.input_boolean.scene_general_on.state == "on" }}'
  action:
  - service: rest_command.konyhapult_generic_on
  - service: timer.start
    entity_id: timer.timer_konyhapult_off
    
- id: konyhapult_light_off
  alias: Konyhapult lekapcs
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_konyhapult_off
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_konyhapult_movie_off
  condition:
  - condition: state
    entity_id: light.konyhapult
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.konyhapult
    
#
# E T K E Z O
#
- id: ep1_lights_on
  alias: EP1 lights on
  trigger:
  - entity_id: binary_sensor.ep1
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ 1*states.sensor.lightlevel_6.state < 39 }}'
  - condition: template
    value_template: '{{ states.input_boolean.scene_sleepy_home_on.state == "off" }}'    
  action:
  - service: timer.start
    entity_id: timer.timer_ep1_lights
  - service: switch.turn_on
    entity_id: switch.el1r1_5
    data:
      entity_id: el1r5
  - service: switch.turn_on
    entity_id: switch.el2r1_6
    data:
      entity_id: el2r6
  - service: switch.turn_on
    entity_id: switch.el3r1_7
    data:
      entity_id: el3r7

- id: ep1_lights_off
  alias: EP1 lights off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_ep1_lights
  condition:
  - condition: state
    entity_id: binary_sensor.ep1
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.el1r1_5
  - service: switch.turn_off
    entity_id: switch.el2r1_6
  - service: switch.turn_off
    entity_id: switch.el3r1_7

#
# N A P P A L I  1
#
- id: np1_lights_on
  alias: NP1 lights on
  trigger:
  - entity_id: binary_sensor.np1
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_6
    below: 39
  - condition: template
    value_template: '{{ states.input_boolean.scene_sleepy_home_on.state == "off" }}'
  action:
  - service: timer.start
    entity_id: timer.timer_np1_lights
  - service: switch.turn_on
    entity_id: switch.nl1r1_1
    data:
      entity_id: nl1r1
  - service: switch.turn_on
    entity_id: switch.nl2r1_2
    data:
      entity_id: nl2r2
- id: np1_lights_off
  alias: NP1 lights off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_np1_lights
  condition:
  - condition: state
    entity_id: binary_sensor.np1
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.nl1r1_1
  - service: switch.turn_off
    entity_id: switch.nl2r1_2
    
#
# N A P P A L I  2
#
- id: np2_lights_on
  alias: NP2 lights on
  trigger:
  - entity_id: binary_sensor.np2
    from: 'off'
    platform: state
    to: 'on'
  condition:  
  - condition: numeric_state
    entity_id: sensor.lightlevel_6
    below: 39
  - condition: template
    value_template: '{{ states.input_boolean.scene_sleepy_home_on.state == "off" }}'
  action:
  - service: timer.start
    entity_id: timer.timer_np2_lights
  - service: switch.turn_on
    entity_id: switch.nl3r1_3
    data:
      entity_id: nl3r3
  - service: switch.turn_on
    entity_id: switch.nl2r1_2
    data:
      entity_id: nl2r2

- id: np2_lights_off
  alias: NP2 lights off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_np2_lights
  condition:
  - condition: state
    entity_id: binary_sensor.np2
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.nl3r1_3
  - service: switch.turn_off
    entity_id: switch.nl2r1_2

#
# P R E S E N C E   R E L A T E D
#
- id: noone_at_home
  alias: Üres a ház
  trigger:
  - platform: state
    entity_id: group.csalad
    from: 'home'
    to: 'not_home'
  action:
  - service: switch.turn_off
    entity_id: group.downstairs
  - service: light.turn_off
    entity_id: group.all_lights

- id: valaki_megjott
  alias: Valaki hazajött
  trigger:
  - platform: state
    entity_id: group.csalad
    from: 'not_home'
    to: 'home'
  condition:  
  - condition: numeric_state
    entity_id: sensor.lightlevel_6
    below: 39    
  action:
  - service: switch.turn_on
    entity_id: group.downstairs
  - service: timer.start
    entity_id: timer.timer_welcome_home

- id: valaki_megjott_off
  alias: Valaki hazajött kikapcs
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      event_id: timer.timer_welcome_home
  action:
  - service: switch.turn_off
    entity_id: group.downstairs
  - service: input_boolean.turn_on
    entity_id: input_boolean.scene_general_on

#
# H A L O S Z O B A I   F O L Y O S O
#
- id: halo_folyoso_mozgas
  alias: Háló folyosó
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.halofoyosopir'
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_6
    below: 39    
  - condition: template
    value_template: '{{ states.sensor.daylight.attributes.daylight == False }}'
  - condition: template
    value_template: '{{ states.input_boolean.scene_sleepy_home_on.state == "off" }}'
  - condition: time
    after: '06:20:00'
    before: '22:00:00'
  action:
  - service: light.turn_on
    data:
      entity_id: light.halofolyoso
      brightness: 255
      kelvin: 2700
  - service: timer.start
    entity_id: timer.timer_halo_folyoso_ki

- id: halo_folyoso_ki
  alias: Háló folyosó kikapcsol
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_halo_folyoso_ki
  action:
  - service: light.turn_off
    entity_id: light.halofolyoso
