- id: ep1_lights_on
  alias: EP1 lights on
  trigger:
  - entity_id: binary_sensor.ep1
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: timer.start
    entity_id: timer.timer_ep1_lights
  - service: switch.turn_on
    entity_id: switch.el1r1_5
    data:
      entity_id: el1r5
  - service: switch.turn_on
    entity_id: switch.el2r1_6
    data:
      entity_id: el2r6
  - service: switch.turn_on
    entity_id: switch.el3r1_7
    data:
      entity_id: el3r7

- id: ep1_lights_off
  alias: EP1 lights off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_ep1_lights
  condition:
  - condition: state
    entity_id: binary_sensor.ep1
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.el1r1_5
  - service: switch.turn_off
    entity_id: switch.el2r1_6
  - service: switch.turn_off
    entity_id: switch.el3r1_7
#
# N A P P A L I  1
#
- id: np1_lights_on
  alias: NP1 lights on
  trigger:
  - entity_id: binary_sensor.np1
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: timer.start
    entity_id: timer.timer_np1_lights
  - service: switch.turn_on
    entity_id: switch.nl1r1_1
    data:
      entity_id: nl1r1
  - service: switch.turn_on
    entity_id: switch.nl2r1_2
    data:
      entity_id: nl2r2
- id: np1_lights_off
  alias: NP1 lights off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_np1_lights
  condition:
  - condition: state
    entity_id: binary_sensor.np1
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.nl1r1_1
  - service: switch.turn_off
    entity_id: switch.nl2r1_2
#
# N A P P A L I  2
#
- id: np2_lights_on
  alias: NP2 lights on
  trigger:
  - entity_id: binary_sensor.np2
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: timer.start
    entity_id: timer.timer_np2_lights
  - service: switch.turn_on
    entity_id: switch.nl3r1_3
    data:
      entity_id: nl3r3
  - service: switch.turn_on
    entity_id: switch.nl2r1_2
    data:
      entity_id: nl2r2

- id: np2_lights_off
  alias: NP2 lights off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_np2_lights
  condition:
  - condition: state
    entity_id: binary_sensor.np2
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.nl3r1_3
  - service: switch.turn_off
    entity_id: switch.nl2r1_2

- id: noone_at_home
  alias: Üres a ház
  trigger:
  - platform: state
    entity_id: group.csalad
    from: 'home'
    to: 'not_home'
  action:
  - service: switch.turn_off
    entity_id: group.downstairs
  - service: light.turn_off
    entity_id: group.all_lights

- id: valaki_megjott
  alias: Valaki haza jött
  trigger:
  - platform: state
    entity_id: group.csalad
    from: 'not_home'
    to: 'home'
  action:
  - service: switch.turn_on
    entity_id: group.downstairs

#
# H A L O S Z O B A I   F O L Y O S O
#
- id: halo_folyoso_mozgas
  alias: Háló folyosó
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.halofoyosopir'
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.halofolyoso
    state: 'off'
  - condition: template
    value_template: '{{ states.sensor.daylight.attributes.daylight == False }}'
  - condition: time
    after: '06:00:00'
    before: '22:00:00'     
  action:
  - service: light.turn_on
    entity_id: light.halofolyoso
  - service: timer.start
    entity_id: timer.timer_halo_folyoso_ki

- id: halo_folyoso_ki
  alias: Háló folyosó kikapcsol
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_halo_folyoso_ki
  condition:
  - condition: state
    entity_id: 'binary_sensor.halofoyosopir'
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: light.halofolyoso

