homeassistant:
  # Name of the location where Home Assistant is running
  # https://www.latlong.net/c/?lat=47.440428&long=19.032435
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.440428
  longitude: 19.032435
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 105
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Budapest
  # Customization file
  customize: !include customize.yaml

  customize_glob:
    "sensor.dark_sky_*":
      hidden: true

    "timer.timer_*":
      hidden: true

  auth_providers:
    - type: homeassistant

lovelace:
  mode: yaml
  resources:
    - url: /local/shutter.js
      type: js
    - url: /local/mini-graph-card-bundle.js?v=0.9.3
      type: module
    - url: /local/button-card/button-card.js?v=0.10.2
      type: module
    - url: /local/fkf-garbage-collection-card/dist/fkf-garbage-collection-card.js
      type: js
    - url: /local/slider-entity-row.js
      type: module
    - url: /hacsfiles/PlantPictureCard/PlantPictureCard.js
      type: module
    - url: /local/layout-card.js
      type: module

#    "binary_sensor.*p*":
#      hidden: true
system_health:

zeroconf:

ios:
  actions:
    - name: nappali_lamba
      background_color: "#00001f"
      label: 
        text: "Nappali"
        color: "#ffffff"

evohome:
  username: !secret tcc_username
  password: !secret tcc_password

logger:
  default: warning
  logs:
    pydeconz: info
    homeassistant.components.deconz: info
    custom_components.mitemp_bt: info
zone:
  - name: Home
    latitude: 47.440428
    longitude: 19.032435
    radius: 50
    icon: mdi:account-multiple
  - name: WorldQuant
    latitude: 47.505235
    longitude: 19.050571
    radius: 50
    icon: mdi:factory
  - name: Osztrak Iskola
    latitude: 47.498961
    longitude: 19.011734
    radius: 50
    icon: mdi:school
  - name: Tamasi
    latitude: 47.492178
    longitude: 19.004202
    radius: 50
    icon: mdi:school

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  #api_password: !secret legacy_http_password
  #base_url: https://patvarutca4.duckdns.org
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  #use_x_forwarded_for: true
  #trusted_proxies:
  #  - 127.0.0.1
  #  - ::1
  # ssl_profile: intermediate

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

recorder:
  purge_keep_days: 30
  include:
    domains:
      - sensor
      - light
      - switch
      - media_player
      - automation
      - binary_sensor
      - sun
      - device_tracker
      - input_number
    entities:
      - group.csalad
      - group.downstairs
      - group.bathroom_windows
  exclude:
    entity_globs:
      - sensor.weather_*
      - sensor.dark_sky_*
    entities:
     - sun.sun
     - sensor.last_boot
     - sensor.date
     - sensor.time

mobile_app:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sensor
      - light
      - switch
      - media_player
      - binary_sensor
      - sun
      - device_tracker
      - person
    entities:
      - group.csalad
      - group.downstairs
      - group.bathroom_windows
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date


# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: Grafana
#  password: Grafana
#  max_retries: 3
#  default_measurement: state

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.100-200
    home_interval: 10
    exclude:
     - 192.168.0.107
     - 192.168.0.199
     - 192.168.0.151
     - 192.168.0.166
     - 192.168.0.186
     - 192.168.0.171
     - 192.168.0.126
#  - platform: icloud
#    username: !secret tamas_icloud_user
#    password: !secret tamas_icloud_password
#    gps_accuracy_threshold: 200
#    account_name: Tamas
#  - platform: icloud
#    username: !secret csongor_icloud_user
#    password: !secret csongor_icloud_password
#    gps_accuracy_threshold: 200
#    account_name: Csongor


# Track the sun
sun:

# Weather prediction
weather:
  - platform: darksky
    api_key: !secret dark_sky_api


sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
# Text to speech
#tts:
#  - platform: google_translate
#    service_name: google_say

# Cloud
# cloud:

#no_ip:
#  domain: gergely.ddns.net
#  username: !secret ddns_user
#  password: !secret ddns_password

# media_player:
#   - platform: denonavr
#     host: 192.168.0.151
#     name: Home-Theater
#     show_all_sources: True

# apple_tv_mrp:
#   - name: Wohnzimmer
#     host: 192.168.0.171
#     port: 49153

#  - platform: firetv
#    name: FireTV
#    host: 192.168.0.167

input_text:
  working_shutter_up_time:
    name: Shutter up while working
    pattern: '[0-2]?[0-9]:[0-5][0-9]'
    initial: '11:45'
  summer_shutter_up_time:
    name: Shutter up in the summer
    pattern: '[0-2]?[0-9]:[0-5][0-9]'
    initial: '11:45'

input_datetime:
  wake_up_time:
    name: Wake up time
    has_date: false
    has_time: true
  sleep_time:
    name: Sleep time
    has_date: false
    has_time: true
  general_scene_time:
    name: General time
    has_date: false
    has_time: true
  stairs_ambient_off_time:
    name: Stairs auto-off
    has_date: false
    has_time: true
  sidewall_cover_move_start_time:
    name: Ablak redony mozgas bekapcs
    has_date: false
    has_time: true
  livingroom_cover_move_start_time:
    name: Nappali redony mozgas bekapcs
    has_date: false
    has_time: true
  kitchen_cover_move_start_time:
    name: Konyhai redony mozgas bekapcs
    has_date: false
    has_time: true

input_select:
  scene_home:
    name: Scene
    options:
      - General
      - Movie
      - Sleepy
      - WakeUp
      - Working

input_boolean:
  extended_shutter_control:
    name: Extra redony beallitasok
    initial: off
  summer_heat_mode:
    name: Nyári kánikula mód
    initial: off
  auto_ambiance_mode:
    name: Automata hangulatvilágítás
    initial: on
  ambient_stair_spots:
    name: Lépcső hangulatvilágítás
  auto_cover_for_movie_scene:
    name: Redőny le mozi kozben
    initial: on
  automatic_kitchen_light_on:
    name: Konyhalampa automatikusan kapcsolt
  automatic_livingroom_light_on:
    name: Nappali automatikusan kapcsolt
  automatic_bathroom_lights:
    name: Automata furdo lampa

camera:
  - platform: mjpeg
    name: gpcam
    verify_ssl: false
    still_image_url: "http://192.168.0.107:8123/api/hassio_ingress/3R2tWgpcUvxr0djlFLs__6TpoJVbjXRAg0MqtDDKNKs/picture/1/current/?_username=admin&_signature=4126904ea62cee05cda1b7a9219c6da7e3f424f1"
    mjpeg_url: "http://192.168.0.107:8081/"
    authentication: digest
    username: !secret camera_surveilance_user
    password: !secret camera_surveilance_password

notify:
  - name: csilla_tamas_phone
    platform: group
    services:
      - service: mobile_app_iphone_von_tamas
      - service: mobile_app_csilla_iphone_ja
  - name: tamas
    platform: group
    services:
      - service: mobile_app_iphone_von_tamas

plant:
  anthurium_andraeanum:
    sensors:
      moisture: sensor.mi_m_c47c8d6bae31
      temperature: sensor.mi_t_c47c8d6bae31
      conductivity: sensor.mi_c_c47c8d6bae31
      brightness: sensor.mi_l_c47c8d6bae31
    min_moisture: 15  
  gummibaum:
    sensors:
      moisture: sensor.mi_moisture_c47c8d6b9d96
      brightness: sensor.mi_llluminance_c47c8d6b9d96
      conductivity: sensor.mi_conductivity_c47c8d6b9d96
      temperature: sensor.mi_temperature_c47c8d6b9d96
    min_moisture: 15
  orchidea:
    sensors:
      moisture: sensor.mi_moisture_c47c8d6b9e36
      brightness: sensor.mi_llluminance_c47c8d6b9e36
      conductivity: sensor.mi_conductivity_c47c8d6b9e36
      temperature: sensor.mi_temperature_c47c8d6b9e36
    min_moisture: 0
  dracanea_fragrans:
    sensors:
      moisture: sensor.mi_moisture_c47c8d6b9d4e
      brightness: sensor.mi_llluminance_c47c8d6b9d4e
      conductivity: sensor.mi_conductivity_c47c8d6b9d4e
      temperature: sensor.mi_temperature_c47c8d6b9d4e
    min_moisture: 15


input_number: !include input_numbers.yaml
timer: !include timers.yaml
group: !include groups.yaml
#automation: !include automations.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include shell_commands.yaml
person: !include persons.yaml