homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.440449
  longitude: 19.032424
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 17
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Budapest
  # Customization file
  customize: !include customize.yaml

  customize_glob:
    "sensor.dark_sky_*":
      hidden: true

    "timer.timer_*":
      hidden: true
  
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

lovelace:
   mode: yaml
  
#    "binary_sensor.*p*":
#      hidden: true
system_health:

ios:

logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug

zone:
  - name: Home
    latitude: 47.440449
    longitude: 19.032424
    radius: 50
    icon: mdi:account-multiple
  - name: WorldQuant
    latitude: 47.505235
    longitude: 19.050571
    radius: 50
    icon: mdi:factory
  - name: Osztrak Iskola
    latitude: 47.498961
    longitude: 19.011734
    radius: 50
    icon: mdi:school
  - name: Tamasi
    latitude: 47.492178
    longitude: 19.004202
    radius: 50
    icon: mdi:school
    
# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret legacy_http_password
  base_url: http://patvarutca4.duckdns.org:443
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # ssl_profile: intermediate
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: Grafana
  password: Grafana
  max_retries: 3
  default_measurement: state

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.100-200
    home_interval: 10
    exclude:
     - 192.168.0.107
     - 192.168.0.199
     - 192.168.0.151
     - 192.168.0.166
     - 192.168.0.186
     - 192.168.0.126  
#  - platform: icloud
#    username: !secret tamas_icloud_user
#    password: !secret tamas_icloud_password
#    gps_accuracy_threshold: 200
#    account_name: Tamas
#  - platform: icloud
#    username: !secret csongor_icloud_user
#    password: !secret csongor_icloud_password
#    gps_accuracy_threshold: 200
#    account_name: Csongor


# Track the sun
sun:

# Weather prediction
weather:
  - platform: darksky
    api_key: !secret dark_sky_api


sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
# Text to speech
tts:
  - platform: google

# Cloud
# cloud:

no_ip:
  domain: gergely.ddns.net
  username: !secret ddns_user
  password: !secret ddns_password

media_player:
  - platform: denonavr
    host: 192.168.0.151
    name: Home-Theater
    show_all_sources: True

input_boolean:
  scene_sleepy_home_on:
    name: Sleepy Home Scene
    initial: off
  scene_movie_on:
    name: Movie Scene
    initial: off
  scene_general_on:
    name: General Scene
    initial: on
    
rest_command:
  konyhapult_generic_on:
    url: 'http://192.168.0.107:8080/api/FF902BF89F/lights/5/state'
    method: PUT
    payload: '{"on": true, "hue":48350, "bri":255}'
    content_type:  'application/json; charset=utf-8'
  konyhapult_movie_on:
    url: 'http://192.168.0.107:8080/api/FF902BF89F/lights/5/state'
    method: PUT
    payload: '{"on": true, "hue":3000, "bri":150}'
    content_type:  'application/json; charset=utf-8'
  konyhapult_sleepy_on:
    url: 'http://192.168.0.107:8080/api/FF902BF89F/lights/5/state'
    method: PUT
    payload: '{"on": true, "hue":3000, "bri":50}'
    content_type:  'application/json; charset=utf-8'
  plafon_light_movie:
    url: 'http://192.168.0.107:8080/api/2D1E7F2F3B/lights/2/state'
    method: PUT
    payload: '{"on": true, "hue": 2047, "bri": 150 }'
    content_type:  'application/json'
    verify_ssl: false
  fal_light_movie:
    url: 'http://192.168.0.107:8080/api/2D1E7F2F3B/lights/1/state'
    method: PUT
    payload: '{"on": true, "hue": 2047, "bri": 150 }'
    content_type:  'application/json'
    verify_ssl: false    
  plafon_light:
    url: 'http://192.168.0.107:8080/api/2D1E7F2F3B/lights/2/state'
    method: PUT
    payload: '{"on": {{ state }}, "hue": {{ hue }}, "bri": {{ brightness }} }'
    content_type:  'application/json'
    verify_ssl: false
  fal_light:
    url: 'http://192.168.0.107:8080/api/2D1E7F2F3B/lights/1/state'
    method: PUT
    payload: '{"on": {{ state }}, "hue": {{ hue }}, "bri": {{ brightness }} }'
    content_type:  'application/json'
    verify_ssl: false

#shutter:
#  - platform: statefullshutter
#    entity_id: shutter.kitchen
#    name: Konyha redony
#    switches:
#      - "switch.ro1_f_r2_4"
#      - "switch.ro1_l_r2_2"

notify:
  - name: csilla_tamas_phone
    platform: group
    services:
      - service: ios_tamasphone
      - service: ios_csilla_iphoneja
  - name: tamas
    platform: group
    services:
      - service: ios_tamasphone

camera:
  - platform: onvif     
    name: front_cam
    host: 192.168.100.17
    username: !secret cam_user
    password: !secret cam_password

  - platform: ffmpeg
    name: front_cam_ffmpeg
    input: rtsp://admin:0718@192.168.100.17:8554/1.3gp
#    still_image_url: http://192.168.100.14/img/
#    stream_source: rtsp://192.168.100.14:8554/1.3gp
#    authentication: basic
#    framerate: 5
#    verify_ssl: false

input_number: !include input_numbers.yaml
timer: !include timers.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
