resources:
  - url: /local/shutter.js
    type: js
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
    type: module
    
views:
  - title: Main
    path: main
    cards:
      - type: picture-glance
        title: Kamera
        entities:
          - camera.patvarcam
        camera_image: camera.patvarcam    
      - type: glance
        entities:
          - binary_sensor.teraszajto
          - binary_sensor.konyhaajto
          - binary_sensor.openclose_10
          - binary_sensor.openclose_11
          - binary_sensor.openclose_9
      - type: glance
        entities:
          - sensor.temperature_15
          - sensor.temperature_12
      - type: custom:weather-card
        entity: weather.dark_sky      

  - title: Lámpák
    path: lights
    cards:
      - type: entities
        title: Nappali
        entities:
          - type: entity-button
            entity: switch.nl1_r1_1
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.nl2_r1_2
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.nl3_r1_3
            tap_action:
              action: toggle
      - type: entities
        title: Ebédlő
        entities:
          - type: entity-button
            entity: switch.el1_r1_5
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.el2_r1_6
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.el3_r1_7
            tap_action:
              action: toggle
      - type: entities
        title: Konyha
        entities:
          - type: light
            entity: light.konyhapult
          - type: glance
            entity: binary_sensor.presence_2_2
            secondary_info: last-changed
            format: relative
      - type: entities
        title: Ambiente
        entities:
          - type: light
            entity: light.fal
          - type: light
            entity: light.plafon

  - title: Házimozi
    path: media
    cards:
      - type: media-control
        entity: media_player.home_theater
      - type: media-control
        entity: media_player.apple_tv

  - title: Státusz
    path: state
    cards:
      - type: entities
        title: Család
        show_header_toggle: false
        entities:
          - device_tracker.dalma_iphone
          - type: section
            label: Csongor
          - type: glance
            entity: device_tracker.csongor_iphoneja
          - type: sensor
            entity: sensor.csongor_iphone_ja_battery_level
            graph: line
            detail: 2
            unit: '%'
            hours_to_show: 24
          - type: section
            label: Csilla
          - type: glance
            entity: device_tracker.csilla_iphoneja
          - type: sensor
            entity: sensor.csilla_iphone_ja_battery_level
            graph: line
            detail: 2
            unit: '%'
            hours_to_show: 24
          - type: section
            label: Tamas
          - type: glance
            entity: device_tracker.tamasphone
          - type: sensor
            entity: sensor.iphone_von_tamas_battery_level
            graph: line
            detail: 2
            unit: '%'
            hours_to_show: 24

      - type: sensor
        entity: sensor.lightlevel_6
        graph: line
        unit: lux
        detail: 2
        hours_to_show: 24
      - type: sensor
        entity: sensor.temperature_3_2
        graph: line
        unit: C
        detail: 2
        hours_to_show: 24
      - type: gauge
        entity: sensor.wireless_broadband_router_kbyte_sec_received
        name: Internet speed
        unit: 'kb/sec'
        min: 0
        max: 2000
      - type: sensor
        entity: sensor.time  
  
      - type: sensor
        entity: input_boolean.summer_heat_mode
        name: Nyári kánikula
        
  - title: Redonyok
    path: redonyok
    cards:
     - type: entities
       title: Redonyok
       show_header_toggle: false
       entities:
          - type: entity
            entity: cover.kitchen
            label: Konyha
          - type: entity
            entity: input_number.kitchen_shutter_state
          - type: section
          - type: entity
            entity: cover.livingroom
            label: Redőny
          - type: entity
            entity: input_number.livingroom_shutter_state
     - type: conditional
       conditions:
       - entity: input_boolean.extended_shutter_control
         state: "on"
       card:
         type: entities
         entities:
           - type: entity-button
             entity: input_boolean.livingroom_shutter_on
             name: Nappali redony
           - entity: switch.ro1_l_r2_2
             name: Nappali le
           - entity: switch.ro1_f_r2_4 
             name: Nappali fel 
           - type: section  
           - type: entity-button
             entity: input_boolean.kitchen_shutter_on
             name: Konyhai redony  
           - entity: switch.ro2_l_r2_1
             name: Konyha le
           - entity: switch.ro2_f_r2_3 
             name: Konyha fel 
  - title: Scenen
    path: scenen
    cards:
     - type: entities       
       title: Scenen
       show_header_toggle: false
       entities:
         - type: entity-button
           entity: input_boolean.scene_general_on
         - type: entity-button
           entity: input_boolean.scene_movie_on
         - type: entity-button
           entity: input_boolean.scene_sleepy_home_on

  - title: Beállítások
    path: settings
    cards:
     - type: entities
       title: Szellöztetés
       show_header_toggle: false
       entities:
         - entity: input_number.furdo_szelloztetesi_ido
         - entity: input_number.halo_szelloztetesi_ido
         - type: section
         - entity: input_boolean.extended_shutter_control
           name: Extra redony vezérlés
