resources:
  - url: /local/shutter.js
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.5.0
    type: module
  - url: /local/button-card/button-card.js
    type: module
views:
  - title: Main
    path: main
    panel: true
    cards:
      - type: horizontal-stack
        cards:
        - type: vertical-stack
          cards:
          - type: horizontal-stack
            cards:
            - type: entity-button
              name: Nappali
              entity: switch.nl2_r1_2
              icon: mdi:lightbulb-outline
              icon_height: 30pt
            - type: entity-button
              name: Étkező
              entity: switch.el2_r1_6
              icon: mdi:lightbulb-outline
              icon_height: 30pt
          - type: conditional
            conditions: 
            - entity: media_player.home_theater
              state: "on"
            card:
              type: horizontal-stack
              cards:
                - type: "custom:button-card"
                  color_type: blank-card
                - type: "custom:button-card"
                  color_type: blank-card
                - type: "custom:button-card"
                  color_type: card
                  color: rgb(223, 255, 97)
                  icon: mdi:volume-plus
                  tap_action:
                    action: call-service
                    service: media_player.volume_up
                    service_data:
                      entity_id: media_player.home_theater
                - type: "custom:button-card"
                  color_type: card
                  color: rgb(223, 255, 97)
                  icon: mdi:volume-minus
                  tap_action:
                    action: call-service
                    service: media_player.volume_down
                    service_data:
                      entity_id: media_player.home_theater
                - type: "custom:button-card"
                  color_type: blank-card
                - type: "custom:button-card"
                  color_type: blank-card
          - type: conditional
            conditions:
            - entity: media_player.home_theater_2
              state: "playing"
            card:    
              type: media-control
              entity: media_player.home_theater_2
          - type: conditional
            conditions:
            - entity: media_player.wohnzimmer
              state: "playing"
            card:    
              type: media-control
              entity: media_player.wohnzimmer
          - type: weather-forecast
            entity: weather.home
        - type: vertical-stack
          cards:
          - type: horizontal-stack
            cards:
            - type: glance
              title: Nappali
              entities:
                - entity: sensor.temperature_2
                  name: ""
                - entity: sensor.humidity_3
                  name: ""
            - type: glance
              title: Fürdő
              entities:
                - entity: sensor.temperature_12
                  name: ""
                - entity: sensor.humidity_13
                  name: ""
                - entity: binary_sensor.openclose_11
                  name: ""
                - entity: binary_sensor.openclose_15
                  name: ""
          - type: vertical-stack
            cards:
            - type: horizontal-stack
              cards:
              - type: light
                name: Plafon
                entity: light.livingroom_ceiling
              - type: light
                name: Fal
                entity: light.livingroom_wall
            - type: light
              name: Folyosó
              entity: light.foyer
  - title: Mobile
    path: mobile
    panel: true
    cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: entity-button
            name: Nappali
            entity: switch.nl2_r1_2
            icon: mdi:lightbulb-outline
            icon_height: 30pt
          - type: entity-button
            name: Étkező
            entity: switch.el2_r1_6
            icon: mdi:lightbulb-outline
            icon_height: 30pt
        - type: conditional
          conditions: 
          - entity: media_player.home_theater
            state: "on"
          card:
            type: horizontal-stack
            cards:
              - type: "custom:button-card"
                color_type: blank-card
              - type: "custom:button-card"
                color_type: blank-card
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:volume-plus
                tap_action:
                  action: call-service
                  service: media_player.volume_up
                  service_data:
                    entity_id: media_player.home_theater
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:volume-minus
                tap_action:
                  action: call-service
                  service: media_player.volume_down
                  service_data:
                    entity_id: media_player.home_theater
              - type: "custom:button-card"
                color_type: blank-card
              - type: "custom:button-card"
                color_type: blank-card
        - type: conditional
          conditions:
          - entity: media_player.home_theater_2
            state: "playing"
          card:    
            type: media-control
            entity: media_player.home_theater_2
        - type: conditional
          conditions:
          - entity: media_player.wohnzimmer
            state: "playing"
          card:    
            type: media-control
            entity: media_player.wohnzimmer
        - type: weather-forecast
          entity: weather.home
        - type: horizontal-stack
          cards:
          - type: glance
            title: Nappali
            entities:
              - entity: sensor.temperature_2
                name: ""
              - entity: sensor.humidity_3
                name: ""
          - type: glance
            title: Fürdő
            entities:
              - entity: sensor.temperature_12
                name: ""
              - entity: sensor.humidity_13
                name: ""
              - entity: binary_sensor.openclose_11
                name: ""
              - entity: binary_sensor.openclose_15
                name: ""
        - type: vertical-stack
          cards:
          - type: horizontal-stack
            cards:
            - type: light
              name: Plafon
              entity: light.livingroom_ceiling
            - type: light
              name: Fal
              entity: light.livingroom_wall
          - type: light
            name: Folyosó
            entity: light.foyer
  - title: Lámpák
    path: lights
    cards:
      - type: vertical-stack
        cards:
          - type: "custom:button-card"
            color_type: label-card
            name: Nappali
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: switch.nl1_r1_1
                icon: mdi:numeric-1-box-outline
                show_name: false
              - type: "custom:button-card"
                entity: switch.nl2_r1_2
                icon: mdi:numeric-2-box-outline
                show_name: false
              - type: "custom:button-card"
                entity: switch.nl3_r1_3
                icon: mdi:numeric-3-box-outline
                show_name: false
              - type: "custom:button-card"
                entity: group.living_room
                show_name: false
                state:
                  - value: 'on'
                    icon: mdi:eye-off
                  - value: 'off'
                    icon: mdi:eye
          - type: "custom:button-card"
            color_type: label-card
            name: Konyha
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: switch.el1_r1_5
                icon: mdi:numeric-1-box-outline
                show_name: false
              - type: "custom:button-card"
                entity: switch.el2_r1_6
                icon: mdi:numeric-2-box-outline
                show_name: false
              - type: "custom:button-card"
                entity: switch.el3_r1_7
                icon: mdi:numeric-3-box-outline
                show_name: false     
              - type: "custom:button-card"
                entity: group.kitchen
                show_name: false
                state:
                  - value: 'on'
                    icon: mdi:eye-off
                  - value: 'off'
                    icon: mdi:eye
      - type: entities
        title: Konyha
        entities:
          - type: light
            entity: light.kitchen
          - type: glance
            entity: binary_sensor.presence_5
            secondary_info: last-changed
            format: relative
      - type: entities
        title: Ambiente
        entities:
          - type: light
            entity: light.livingroom_ceiling
          - type: light
            entity: light.livingroom_wall

  - title: Házimozi
    path: media
    cards:
      - type: media-control
        entity: media_player.home_theater
      - type: media-control
        entity: media_player.apple_tv

  - title: Státusz
    path: state
    cards:
      - type: entities
        title: Család
        show_header_toggle: false
        entities:
          - device_tracker.dalma_iphone
          - type: section
            label: Csongor
          - type: glance
            entity: device_tracker.csongor_iphoneja
          - type: sensor
            entity: sensor.csongor_iphone_ja_battery_level
            graph: line
            detail: 2
            unit: '%'
            hours_to_show: 24
          - type: section
            label: Csilla
          - type: glance
            entity: device_tracker.csilla_iphoneja
          - type: sensor
            entity: sensor.csilla_iphone_ja_battery_level
            graph: line
            detail: 2
            unit: '%'
            hours_to_show: 24
          - type: section
            label: Tamas
          - type: glance
            entity: device_tracker.tamasphone
          - type: sensor
            entity: sensor.iphone_von_tamas_battery_level
            graph: line
            detail: 2
            unit: '%'
            hours_to_show: 24

      - type: custom:mini-graph-card
        name: Hőmérséklet
        entities: 
        - sensor.dark_sky_temperature
        align_state: center
        show:
          extrema: true
          points: true
        graph: line
        unit: C
        detail: 2
        hours_to_show: 24
      - type: gauge
        entity: sensor.wireless_broadband_router_kbyte_sec_received
        name: Internet speed
        unit: 'kb/sec'
        min: 0
        max: 2000
      - type: sensor
        entity: sensor.time  
  
      - type: glance
        entities:
          - entity: input_boolean.summer_heat_mode
            name: Nyári kánikula        

  - title: Redonyok
    path: redonyok
    cards:
     - type: entities
       title: Redonyok
       show_header_toggle: false
       entities:
          - type: entity
            entity: cover.kitchen
            label: Konyha
          - type: entity
            entity: input_number.kitchen_shutter_state
          - type: section
          - type: entity
            entity: cover.livingroom
            label: Redőny
          - type: entity
            entity: input_number.livingroom_shutter_state
     - type: conditional
       conditions:
       - entity: input_boolean.extended_shutter_control
         state: "on"
       card:
         type: entities
         entities:
           - type: entity-button
             entity: input_boolean.livingroom_shutter_on
             name: Nappali redony
           - entity: switch.ro1_l_r2_2
             name: Nappali le
           - entity: switch.ro1_f_r2_4 
             name: Nappali fel 
           - type: section  
           - type: entity-button
             entity: input_boolean.kitchen_shutter_on
             name: Konyhai redony  
           - entity: switch.ro2_l_r2_1
             name: Konyha le
           - entity: switch.ro2_f_r2_3 
             name: Konyha fel 
  - title: Scenen
    path: scenen
    cards:
     - type: entities       
       title: Scenen
       show_header_toggle: false
       entities:
         - type: entity-button
           entity: input_boolean.scene_general_on
         - type: entity-button
           entity: input_boolean.scene_movie_on
         - type: entity-button
           entity: input_boolean.scene_sleepy_home_on

  - title: Beállítások
    path: settings
    cards:
     - type: entities
       title: Szellöztetés
       show_header_toggle: false
       entities:
         - entity: input_number.furdo_szelloztetesi_ido
         - entity: input_number.halo_szelloztetesi_ido
         - type: section
         - entity: input_boolean.extended_shutter_control
           name: Extra redony vezérlés
