resources:
  - url: /local/shutter.js
    type: js
    
views:
  - title: Redonyok
    path: redonyok
    cards:
     - type: entities
       title: Redonyok
       show_header_toggle: false
       entities:
          - type: section
            label: Konyha
          - type: custom:slider-entity-row
            entity: shutter.kitchen_shutter_state
            min: 0
            max: 40
            step: 1
            input_ref: input_number.kitchen_shutter_state
            service_up_ref: kitchen_shutter_open
            service_down_ref: kitchen_shutter_close
          - type: section
            label: Nappali
          - type: custom:slider-entity-row
            entity: shutter.livingroom_shutter_state
            min: 0
            max: 40
            step: 1
            input_ref: input_number.livingroom_shutter_state
            service_up_ref: livingroom_shutter_open
            service_down_ref: livingroom_shutter_close  