resources:
  - url: /local/shutter.js
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.8.2
    type: module
  - url: /local/button-card/button-card.js
    type: module
views:
  - !include lovelace/main_view.yaml
  - !include lovelace/mobile_view.yaml
  - !include lovelace/lights_view.yaml
  - !include lovelace/state_view.yaml
  
#---------------------------------------------------------------------
#- M E D I A
#---------------------------------------------------------------------
  - title: Házimozi
    path: media
    cards:
      - type: media-control
        entity: media_player.home_theater_2
      - type: media-control
        entity: media_player.wohnzimmer
#---------------------------------------------------------------------
#- S C E N E N
#---------------------------------------------------------------------
  - title: Scenen
    path: scenen
    cards:
     - type: entities
       title: Scenen
       show_header_toggle: false
       entities:
         - entity: input_select.scene_home
#---------------------------------------------------------------------
#- S E T T I N G S
#---------------------------------------------------------------------
  - title: Beállítások
    path: settings
    cards:
     - type: entities
       title: Szellöztetés
       show_header_toggle: false
       entities:
         - entity: input_number.furdo_szelloztetesi_ido
           name: Fürdő
         - entity: input_number.halo_szelloztetesi_ido
           name: Hálószoba
     - type: entities
       title: Időzítés
       show_header_toggle: false
       entities:
         - type: section
         - entity: input_text.wake_up_time
           name: Ébredezés [hétköznap]
         - entity: input_text.general_scene_time
           name: Nappali mód
         - entity: input_text.sleep_time
           name: Elalvás
         - type: section
           label: Konyha [perc]
         - entity: input_number.kitchen_light_off_time_movie
           name: mozi közben
         - entity: input_number.kitchen_light_off_time_daylight
           name: nappal
         - entity: input_number.kitchen_light_off_time_dark
           name: sötétben
         - entity: input_number.kitchen_light_off_time_sleepy
           name: élyszaka
     - type: entities
       title: Hangulatvilágítás
       show_header_toggle: false
       entities:
         - type: section
           label: Automatikus kapcsolás [lux]
         - entity: input_number.ambient_on_below_lux
           name: bekapcsol
         - entity: input_number.ambient_off_above_lux
           name: kikapcsol
         - type: section
           label: Lépcső
         - entity: input_boolean.ambient_stair_spots
           name: automata
         - entity: input_number.stair_ambient_brightness
           name: fényerő
         - entity: input_text.stairs_ambient_off_time
           label: lekapcsolás
         - type: section
           label: Nappali
         - entity: input_number.livingroom_ambient_brightness
           name: fényerő
     - type: entities
       title: Egyéb
       show_header_toggle: false
       entities:
         - entity: input_boolean.auto_ambiance_mode
           name: Automatikus hangulatvilágítás
         - entity: input_boolean.auto_cover_for_movie_scene
